### ISSUE TITLE
[FEAT] 사용자 답변에 사용 될 RAG 데이터 토큰화, 임베딩 및 DB저장

### ISSUE THREAD

**Issue by Dongjun96** [anpang1999/HowUp2#7]
## Description
사용자가 질문 할 내용에 답변으로 사용 될 특정 데이터(ex : 경제 산업 동향 등)를 수집 및 가공 후 데이터베이스에 저장하는 코드를 파일 별로 구현하고자 합니다.

## Todo
- [x] 경제 산업 동향 등 사업성 평가에 사용 가능할 데이터 수집
- [x] 데이터 토큰화 및 임베딩 방향에 대한 고찰
- [x] PDF, CSV 등 파일 별 임베딩 코드 구현
