### ISSUE TITLE
[FEAT] 성능 평가 지표를 확인 할 수 있는 RAGAS 코드 구현

### ISSUE THREAD

**Issue by Dongjun96** [anpang1999/HowUp2#8]
## Description
사용자가 RAG데이터로 받은 답변에 대해 성능 평가 지표를 확인 할 수 있는 RAGAS 코드를 구현하고자 합니다.

## Todo
- [x] DB에 인베딩 된 데이터 형식, 위치 확인
- [x] RAGAS 구현을 위한 공부
- [x] 쿼리 토큰화에 필요한 툴 선택 및 코드 구현
